version: 2.1
executors:
    default-image-docker:
        machine:
            image: ubuntu-1604:202004-01



jobs:
    build_app:
     # executor: default-image-docker
      docker:
        - image: amazon/aws-cli:2.0.26
          auth:
            username: ${DOCKERHUB_USERNAME}
            password: ${DOCKERHUB_ACCESS_TOKEN}
      steps:
        - run: 
            name: install git 
            command: |
                yum install -y git 
        - run: 
            name: install brew
            command: |
                sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
        - run: 
            name: test
            command: |
                whereis brew
        - run: 
            name: install
            command: |
                brew install terragrunt
        - run: 
            name: checkout repo
            command: |
                git clone https://${GIT_TOKEN}@github.com/FinalCAD/terraform-lambdas
workflows:
    main:
        jobs:
            ###### DEPLOY TO SANDBOX ################################# 
            - build_app:
                name: checkout
                context: 
                    - ecr-sandbox
                    - ci-lambda	
                filters:
                    branches:
                        only:
                            - circleci-project-setup
            
