version: 2.1
executors:
    default-image-docker:
        machine:
            image: ubuntu-1604:202004-01
            
jobs:
    build_app:
     # executor: default-image-docker
      docker:
        - image: amazon/aws-cli:2.0.26
          auth:
            username: ${DOCKERHUB_USERNAME}
            password: ${DOCKERHUB_ACCESS_TOKEN}
      steps:
        - checkout
        - run: 
            name: install git 
            command: |
                yum install -y git wget unzip zip
        - run:
            name: gen tarball
            command: |
                 pwd  && ls && zip -r9 function.zip . 
        - run: 
            name: install terragrunt
            command: |
                wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.21.11/terragrunt_linux_amd64
        - run: 
            name: configure terragrunt
            command: |
                mv terragrunt_linux_amd64 terragrunt && chmod u+x terragrunt && mv terragrunt /usr/local/bin/terragrunt
        - run: 
            name: test terragrunt
            command: |
                whereis terragrunt && terragrunt --version
        - run: 
            name: install terraform
            command: |
                wget https://releases.hashicorp.com/terraform/0.12.25/terraform_0.12.25_linux_amd64.zip
        - run: 
            name: configure terraform
            command: |
                unzip ./terraform_0.12.25_linux_amd64.zip -d /usr/local/bin
        - run: 
            name: test terragrunt
            command: |
                whereis terraform && terraform --version           
        - run: 
            name: checkout repo
            command: |
                git clone --single-branch --branch lambda-ci https://${GIT_TOKEN}@github.com/FinalCAD/terraform-lambdas
        - run: 
            name: conf
            command: |
                cd && mkdir .aws && echo -e "[profile lambda] \nrole_arn = arn:aws:iam::760240387743:role/tf-ci-lambda\nsource_profile = default" > .aws/config 
        - run: 
            name: conf
            command: |
                cd && echo -e "[default]\naws_access_key_id = ${AWS_ACCESS_KEY_ID}\naws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" > .aws/credentials
        - run: 
            name: prepare
            command: |              
                cp /root/project/function.zip terraform-lambdas/modules/circleci_lambda/lambda_prerequisite/. 
        - run: 
            name: exec
            command: |              
                cd terraform-lambdas/sandbox/frankfurt/ && mkdir ${CIRCLE_PROJECT_REPONAME}  && cd ${CIRCLE_PROJECT_REPONAME} && cp /root/project/terragrunt.hcl . && terragrunt apply  -auto-approve
workflows:
    main:
        jobs:
            ###### DEPLOY TO SANDBOX ################################# 
            - build_app:
                name: checkout
                context: 
                    - ci-lambda	
                filters:
                    branches:
                        only:
                            - circleci-project-setup
            
