version: 2.1
executors:
    default-image-docker:
        machine:
            image: ubuntu-1604:202004-01



jobs:
    build_app:
      executor: default-image-docker
      steps:
        - run: 
            name: Updating Linux packages list
            command: apt-get update
        - run: 
            name: checkout repo
            command: |
                git clone git@github.com:FinalCAD/terraform-lambdas.git
workflows:
    main:
        jobs:
            ###### DEPLOY TO SANDBOX ################################# 
            - build_app:
                name: test
                context: 
                    - ci-lambda	
                    - dockerhub
                filters:
                    branches:
                        only:
                            - circleci-project-setup
            
