version: 2.1
executors:
    default-image-docker:
        machine:
            image: ubuntu-1604:202004-01



jobs:
    build_app:
      executor: default-image-docker
      steps:
        - run: 
            name: checkout repo
            command: |
                env && git clone https://${GIT_TOKEN}@github.com/FinalCAD/terraform-lambdas
workflows:
    main:
        jobs:
            ###### DEPLOY TO SANDBOX ################################# 
            - build_app:
                name: checkout
                context: 
                    - ci-lambda	
                filters:
                    branches:
                        only:
                            - circleci-project-setup
            
