version: 2.1
executors:
    default-image-docker:
        machine:
            image: ubuntu-1604:202004-01



jobs:
    build_app:
     # executor: default-image-docker
      docker:
        - image: amazon/aws-cli:2.0.26
          auth:
            username: ${DOCKERHUB_USERNAME}
            password: ${DOCKERHUB_ACCESS_TOKEN}
      steps:
        - run: 
            name: install git 
            command: |
                yum install -y git wget unzip
        - run: 
            name: install terragrunt
            command: |
                wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.26.7/terragrunt_linux_amd64
        - run: 
            name: configure terragrunt
            command: |
                mv terragrunt_linux_amd64 terragrunt && chmod u+x terragrunt && mv terragrunt /usr/local/bin/terragrunt
        - run: 
            name: test terragrunt
            command: |
                whereis terragrunt && terragrunt --version

        - run: 
            name: install terraform
            command: |
                wget https://releases.hashicorp.com/terraform/0.12.2/terraform_0.12.2_linux_amd64.zip
        - run: 
            name: configure terraform
            command: |
                unzip ./terraform_0.12.2_linux_amd64.zip -d /usr/local/bin
        - run: 
            name: test terragrunt
            command: |
                whereis terraform && terraform --version           
        - run: 
            name: checkout repo
            command: |
                git clone https://${GIT_TOKEN}@github.com/FinalCAD/terraform-lambdas
        - run: 
            name: conf
            command: |
                cd && mkdir .aws && echo -e "[profile test] \nrole_arn = arn:aws:iam::760240387743:role/tf-terraform-developer" > .aws/config 
        - run: 
            name: conf
            command: |
                cd && echo -e "[default]\naws_access_key_id = ${AWS_ACCESS_KEY_ID}\naws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" > .aws/credentials
        - run: 
            name: test
            command: |              
                cd && ls .aws && cat .aws/* && aws s3 ls --profile test
workflows:
    main:
        jobs:
            ###### DEPLOY TO SANDBOX ################################# 
            - build_app:
                name: checkout
                context: 
                    - ecr-sandbox
                    - ci-lambda	
                filters:
                    branches:
                        only:
                            - circleci-project-setup
            
