version: 2.1
executors:
    default-image-docker:
        machine:
            image: ubuntu-1604:202004-01



jobs:
    build_app:
     # executor: default-image-docker
      docker:
        - image: amazon/aws-cli:2.0.26
          auth:
            username: ${DOCKERHUB_USERNAME}
            password: ${DOCKERHUB_ACCESS_TOKEN}
      steps:
        - run: 
            name: prerequisite
            command: |
                yum install -y git && git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew && mkdir ~/.linuxbrew/bin && ln -s ~/.linuxbrew/Homebrew/bin/brew ~/.linuxbrew/bin && brew install terragrunt
        - run: 
            name: checkout repo
            command: |
                git clone https://${GIT_TOKEN}@github.com/FinalCAD/terraform-lambdas
workflows:
    main:
        jobs:
            ###### DEPLOY TO SANDBOX ################################# 
            - build_app:
                name: checkout
                context: 
                    - ecr-sandbox
                    - ci-lambda	
                filters:
                    branches:
                        only:
                            - circleci-project-setup
            
